// import './globals.css'
// import Provider from './provider'
// import ThemeSwitcher from './ThemeSwitcher'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
      
//         <Provider>
//           <ThemeSwitcher/>
//           {children}
//         </Provider>
//       </body>
//     </html>
//   )
// }

import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "./provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>

          {children}
        </Providers>
      </body>
    </html>
  );
}

